//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentureTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineTest
    {
        public int id { get; set; }
        public string Lot { get; set; }
        public string MCFile { get; set; }
        public string MC { get; set; }
        public Nullable<int> NumTables { get; set; }
    }
}
