//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentureTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineTable
    {
        public int tableID { get; set; }
        public Nullable<int> TableNo { get; set; }
        public Nullable<int> NumAddr { get; set; }
        public string FeederMode { get; set; }
    }
}
